alpha_linear: 0.3
beta_recon: 0.2
delta_mono: 0.05
dropout: 0.1
epsilon_spectral: 0.5
fire_diameter: 0.3
gamma_physics: 0.1
hidden_dim: 128
input_dim: 6
koopman_dim: 128
lr: 0.001
num_layers: 2
output_dim: 1
pred_horizon: 10
weight_decay: 1.0e-05
